### ISSUE TITLE
Mythrill report

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-contracts-pools#1]
==== Exception state ====
SWC ID: 110
Type: Informational
Contract: Pools
Function name: walletPools(address,uint256)
PC address: 3301
Estimated Gas Usage: 754 - 1039
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, **out-of-bounds array access**, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: Pools.sol:57
mapping(address => ContributionIndex[]) public walletPools

**Comment by dariusdev** [comment]
Out-of-bounds-access in the automatically generated getter function. This is an informational message which does not impact domain logic.
